import type { KickParams } from "@/lib/audio/sources/drums/drum-machine/types"

export const KICK_DEFAULT: KickParams = {
  waveform: "sine",
  pitchStartHz: 150,
  pitchEndHz: 45,
  sweepMs: 120,
  sweepCurve: 0.25,
  level: 0.9,
  decayMs: 250,
  ampAttackMs: 2,
  ampCurve: 0.1,
  drive: 1.0,
  clickLevel: 0.2,
  clickMs: 6,
  hpDC: 0.995,
  hpCutFreqHz: 28,
  shelfFreqHz: 3000,
  shelfGainDb: 0,
  shelfBypass: false,
  clipThreshold: 0.9,
  clipSoftness: 0.2,
  clipBypass: false,
  distMode: "soft",
  distAmount: 1.0,
  distMix: 0.8,
  distTone: 0.5,
  distEnvEnabled: true,
  distEnvAttackMs: 2,
  distEnvHoldMs: 0,
  distEnvDecayMs: 80,
  distEnvAmount: 0.5,
}

// 909-ish
export const KICK_909: Partial<KickParams> = {
  waveform: "sine",
  level: 1,
  pitchStartHz: 95,
  pitchEndHz: 45,
  sweepMs: 30,
  sweepCurve: 0.5,
  decayMs: 180,
  ampAttackMs: 1,
  drive: 1.2,
  clickLevel: 0.45,
  clickMs: 8,
  hpDC: 0.996,
  hpCutFreqHz: 30,
  shelfFreqHz: 3500,
  shelfGainDb: 2,
  shelfBypass: false,
  clipThreshold: 0.92,
  clipSoftness: 0.2,
  distMode: "soft",
  distAmount: 1.4,
  distMix: 0.85,
  distTone: 0.55,
  distEnvEnabled: true,
  distEnvAttackMs: 1,
  distEnvHoldMs: 1,
  distEnvDecayMs: 60,
  distEnvAmount: 0.6,
}

// 808 plutôt sub
export const KICK_808: Partial<KickParams> = {
  waveform: "sine",
  level: 0.85,
  pitchStartHz: 55,
  pitchEndHz: 38,
  sweepMs: 80,
  sweepCurve: 0.3,
  decayMs: 520,
  ampAttackMs: 2,
  drive: 1.05,
  clickLevel: 0.18,
  clickMs: 5,
  hpDC: 0.995,
  hpCutFreqHz: 28,
  shelfFreqHz: 2500,
  shelfGainDb: 0,
  shelfBypass: true,
  clipThreshold: 0.96,
  clipSoftness: 0.3,
  distMode: "soft",
  distAmount: 0.8,
  distMix: 0.5,
  distTone: 0.6,
  distEnvEnabled: true,
  distEnvAttackMs: 3,
  distEnvHoldMs: 0,
  distEnvDecayMs: 120,
  distEnvAmount: 0.3,
  subEnabled: true,
  subLevel: 0.35,
  subFollowPitch: true,
  subAttackMs: 5,
  subDecayMs: 520,
}

// Techno punchy
export const KICK_TECHNO_PUNCH: Partial<KickParams> = {
  waveform: "sine",
  pitchStartHz: 180,
  pitchEndHz: 55,
  sweepMs: 25,
  sweepCurve: 0.45,
  level: 0.9,
  decayMs: 170,
  ampAttackMs: 0.5,
  ampCurve: 0.1,
  clickLevel: 0.55,
  clickMs: 6,
  preDelayMs: 10,
  distMode: "soft",
  distAmount: 1.6,
  distMix: 0.9,
  distTone: 0.55,
  shelfBypass: false,
  shelfFreqHz: 3500,
  shelfGainDb: 3.5,
  hpCutFreqHz: 32,
  clipThreshold: 0.9,
  clipSoftness: 0.2,
  clipBypass: false,
  distEnvEnabled: true,
  distEnvAttackMs: 1,
  distEnvHoldMs: 0,
  distEnvDecayMs: 60,
  distEnvAmount: 0.6,
  subEnabled: true,
  subLevel: 0.18,
  subFollowPitch: true,
  subFreqHz: 55,
  subAttackMs: 4,
  subDecayMs: 220,
  subDrive: 0.4,
}

// House / club plus rond mais qui claque
export const KICK_HOUSE_CLUB: Partial<KickParams> = {
  waveform: "sine",
  pitchStartHz: 160,
  pitchEndHz: 50,
  sweepMs: 22,
  sweepCurve: 0.4,
  level: 0.88,
  decayMs: 190,
  ampAttackMs: 1.5,
  ampCurve: 0.0,
  clickLevel: 0.6,
  clickMs: 7,
  distMode: "soft",
  distAmount: 1.0,
  distMix: 0.6,
  distTone: 0.6,
  shelfBypass: false,
  shelfFreqHz: 4000,
  shelfGainDb: 4,
  hpCutFreqHz: 35,
  clipThreshold: 0.94,
  clipSoftness: 0.35,
  distEnvEnabled: true,
  distEnvAttackMs: 2,
  distEnvHoldMs: 10,
  distEnvDecayMs: 80,
  distEnvAmount: 0.5,
  noiseEnabled: true,
  noiseLevel: 0.22,
  noiseColor: "band",
  noiseDecayMs: 40,
  noiseBpHz: 4500,
  noiseBpQ: 3.5,
}

// Tribe / acid
export const KICK_TRIBE_HARDFLOOR: Partial<KickParams> = {
  waveform: "sine",
  level: 0.95,
  pitchStartHz: 160,
  pitchEndHz: 55,
  sweepMs: 22,
  sweepCurve: 0.45,
  decayMs: 180,
  ampAttackMs: 0.8,
  drive: 2.2,
  clickLevel: 0.6,
  clickMs: 7,
  hpDC: 0.996,
  hpCutFreqHz: 34,
  distMode: "hard",
  distAmount: 2.5,
  distMix: 0.95,
  distTone: 0.45,
  shelfBypass: false,
  shelfFreqHz: 4500,
  shelfGainDb: 4,
  clipThreshold: 0.85,
  clipSoftness: 0.1,
  distEnvEnabled: true,
  distEnvAttackMs: 1,
  distEnvHoldMs: 5,
  distEnvDecayMs: 60,
  distEnvAmount: 0.7,
  tokEnabled: true,
  tokLevel: 0.3,
  tokWaveform: "square",
  tokHz: 900,
  tokDecayMs: 25,
  tokDrive: 1.5,
}

// Frenchcore slam
export const KICK_FRENCHCORE_SLAM: Partial<KickParams> = {
  waveform: "sawtooth",
  level: 0.9,
  pitchStartHz: 220,
  pitchEndHz: 60,
  sweepMs: 18,
  sweepCurve: 0.3,
  decayMs: 150,
  ampAttackMs: 0.2,
  ampCurve: 0.05,
  clickLevel: 0.65,
  clickMs: 5,
  tokEnabled: true,
  tokWaveform: "square",
  tokLevel: 0.55,
  tokHz: 1200,
  tokSweepMs: 5,
  tokDecayMs: 30,
  tokDrive: 2.5,
  drive: 2.5,
  distMode: "hard",
  distAmount: 3.2,
  distMix: 1,
  distTone: 0.45,
  shelfBypass: false,
  shelfFreqHz: 5000,
  shelfGainDb: 5,
  hpCutFreqHz: 38,
  clipThreshold: 0.8,
  clipSoftness: 0.1,
  clipBypass: false,
  postFilterType: "lp",
  postFilterFreqHz: 9000,
  postFilterQ: 0.7,
  distEnvEnabled: true,
  distEnvAttackMs: 0.5,
  distEnvHoldMs: 5,
  distEnvDecayMs: 50,
  distEnvAmount: 0.7,
  subEnabled: true,
  subLevel: 0.25,
  subFollowPitch: true,
  subFreqHz: 55,
  subAttackMs: 3,
  subDecayMs: 190,
  subDrive: 1.0,
  noiseEnabled: true,
  noiseLevel: 0.25,
  noiseColor: "band",
  noiseDecayMs: 35,
  noiseBpHz: 5500,
  noiseBpQ: 4,
}

// Gabber saw brutal
export const KICK_GABBER_SAW: Partial<KickParams> = {
  waveform: "sawtooth",
  level: 0.9,
  pitchStartHz: 200,
  pitchEndHz: 70,
  sweepMs: 15,
  sweepCurve: 0.35,
  decayMs: 130,
  ampAttackMs: 0.3,
  ampCurve: 0.05,
  clickLevel: 0.6,
  clickMs: 4,
  tokEnabled: true,
  tokWaveform: "square",
  tokLevel: 0.6,
  tokHz: 1500,
  tokSweepMs: 3,
  tokDecayMs: 25,
  tokDrive: 3,
  distMode: "hard",
  distAmount: 3.5,
  distMix: 1,
  distTone: 0.4,
  shelfBypass: false,
  shelfFreqHz: 6000,
  shelfGainDb: 4,
  hpCutFreqHz: 40,
  clipThreshold: 0.78,
  clipSoftness: 0.05,
  distEnvEnabled: true,
  distEnvAttackMs: 0.5,
  distEnvHoldMs: 5,
  distEnvDecayMs: 40,
  distEnvAmount: 0.75,
  subEnabled: true,
  subLevel: 0.2,
  subFollowPitch: true,
  subFreqHz: 60,
  subAttackMs: 2,
  subDecayMs: 160,
  subDrive: 1.2,
}

// Industrial / distorté
export const KICK_INDUSTRIAL_THUMP: Partial<KickParams> = {
  waveform: "triangle",
  level: 0.9,
  pitchStartHz: 120,
  pitchEndHz: 40,
  sweepMs: 35,
  sweepCurve: 0.25,
  decayMs: 260,
  ampAttackMs: 1,
  drive: 2.5,
  clickLevel: 0.45,
  clickMs: 10,
  hpDC: 0.995,
  hpCutFreqHz: 30,
  distMode: "fold",
  distAmount: 2.8,
  distMix: 0.9,
  distTone: 0.5,
  shelfBypass: false,
  shelfFreqHz: 4500,
  shelfGainDb: 2,
  clipThreshold: 0.85,
  clipSoftness: 0.3,
  distEnvEnabled: true,
  distEnvAttackMs: 2,
  distEnvHoldMs: 0,
  distEnvDecayMs: 100,
  distEnvAmount: 0.6,
  noiseEnabled: true,
  noiseLevel: 0.3,
  noiseColor: "white",
  noiseDecayMs: 70,
  noiseHpHz: 3000,
}

// Petit rave core
export const KICK_RAVECORE: Partial<KickParams> = {
  waveform: "sine",
  level: 0.95,
  pitchStartHz: 180,
  pitchEndHz: 48,
  sweepMs: 20,
  sweepCurve: 0.35,
  decayMs: 190,
  ampAttackMs: 0.5,
  drive: 1.8,
  clickLevel: 0.7,
  clickMs: 6,
  hpDC: 0.996,
  hpCutFreqHz: 34,
  distMode: "soft",
  distAmount: 2.0,
  distMix: 0.95,
  distTone: 0.5,
  shelfBypass: false,
  shelfFreqHz: 4800,
  shelfGainDb: 4,
  clipThreshold: 0.86,
  clipSoftness: 0.2,
  distEnvEnabled: true,
  distEnvAttackMs: 1,
  distEnvHoldMs: 5,
  distEnvDecayMs: 70,
  distEnvAmount: 0.6,
}
